- hosts: webservers
  gather_facts: yes
  sudo: yes
  vars:
          mac_list:
                  - "5e:4c:af:6e:25:d7"
          remote_vpc: 3
          remote_subnet: 1
          local_vpc: 4
          local_subnet: 1
  tasks:
          - name: Add routes to fdb
            command: "ip netns exec subnet{{ local_vpc }}-{{ local_subnet }} bridge fdb add {{ item }} dst 1.{{ remote_vpc }}.{{ remote_subnet }}.1 dev vxlan0"
            with_items: "{{ mac_list }}"
