- hosts: webservers
  gather_facts: yes
  sudo: yes
  tasks:
    - name: Delete all providers
      command: "ip netns del provider"
      ignore_errors: yes

    - name: Delete NAT rule
      command: "iptables -t nat -D POSTROUTING -s 3.3.{{ ansible_hostname[-1] }}.0/24 ! -d 3.3.{{ ansible_hostname[-1] }}.0/24 -j MASQUERADE"
      ignore_errors: yes
