
- gather_facts: true
  hosts: webservers
  sudo: true
  vars:
    creation_vars:
      - {edge_number: '0', vpc_id: '8'}

  tasks:
    - name: "Delete edge container"
      docker_container:
        name: "V{{ item.vpc_id }}E{{ item.edge_number }}"
        state: absent
      with_items: "{{ creation_vars }}"
    - name: "Delete edge namespace"
      shell: "ip netns del V{{ item.vpc_id }}E{{ item.edge_number }}"
      with_items: "{{ creation_vars }}"
      ignore_errors: yes
    - name: "Delete edge container"
      shell: "docker rm -f V{{ item.vpc_id }}E{{ item.edge_number }}"
      with_items: "{{ creation_vars }}"
      ignore_errors: yes
    # - name: "Delete iptable rules"
    #   shell: "iptables -t nat -D POSTROUTING -s 2.{{ item.vpc_id }}.{{ item.edge_number }}.0/24 ! -d 2.{{ item.vpc_id }}.{{ item.edge_number }}.0/24 -j MASQUERADE"
    #   with_items: "{{ creation_vars }}"
    #   ignore_errors: yes


