###############################################################################################
## USAGE
## sudo ansible-playbook -i hosts-ini -e '{"edge_number": [EDGE_NUMBER], "vpc_id": [VPC_ID]}' edge-route-to-host.yml
################################################################################################
- gather_facts: true
  hosts: webservers
  sudo: yes
  vars:
    creation_vars:
      - {edge_number: '1', vpc_id: '1' }

  tasks:

    - name: "Adding route from edge to host"
      when: inventory_hostname == 'host2'
      shell: "(ip route | grep 2.{{item.vpc_id}}.{{item.edge_number}}.0/24) || (ip route add 2.{{item.vpc_id}}.{{item.edge_number}}.0/24 via {{ hostvars['host1'].ansible_host }})"
      with_items: "{{ creation_vars }}"

    - name: "Adding route from edge to host"
      when: inventory_hostname == 'host1'
      shell: "(ip route | grep 2.{{item.vpc_id}}.{{item.edge_number}}.0/24) || (ip route add 2.{{item.vpc_id}}.{{item.edge_number}}.0/24 via {{ hostvars['host2'].ansible_host }})"
      with_items: "{{ creation_vars }}"
